### ISSUE TITLE
Weird random range generator

### ISSUE THREAD

**Issue by lineargraph** [JohnnyJayJay/sum-rewrite#2]
https://github.com/JohnnyJayJay/sum-rewrite/blob/8154a849734d78a136dfc12edfe1e3801d87ca5e/src/bettersum/tools/Calculator.java#L26

This function creates an int between two numbers: but rather than returning a number within that range it returns a number within or above that range

**Comment by JohnnyJayJay** [comment]
This is currently intended behaviour.
The method functionality is taken from the original library which lets you specify the minimum and the maximum, both included.
The original code was this:
```java
public int ganzeZufallsZahl(int pVon, int pBis) {
   return Math.abs(this.hatRandom.nextInt()) % (pBis - pVon + 1) + pVon;
}
```
I know that including both range borders is very uncommon. But it is yet to decide if I keep it like that, I can't say for sure in this early state.

**Comment by lineargraph** [comment]
No, what i mean is that this can potentially include numbers till `max + min` and not till `max`

**Comment by JohnnyJayJay** [comment]
You're right, lol. I somehow didn't see that.
Hotfix coming.
