### ISSUE TITLE
Diese codestelle ignoriert das übergebene Argument

### ISSUE THREAD

**Issue by lineargraph** [JohnnyJayJay/sum-rewrite#5]
https://github.com/JohnnyJayJay/sum-rewrite/blob/8154a849734d78a136dfc12edfe1e3801d87ca5e/src/bettersum/tools/Clock.java#L58

**Comment by JohnnyJayJay** [comment]
Tut sie nicht :)
Die TimeUnit-Instanz, die dort übergeben wird, wird genutzt, um das Intervall umzuwandeln.
